local Assets = {
	Images = {
		WidgetButton = "rbxassetid://95866080",
		RefreshButtonDark = "rbxassetid://17210895174",
		RefreshButtonLight = "rbxassetid://17210880996",

		DefaultMacroIcon = "rbxassetid://95866080",

		ColorPickerHueSat = "rbxassetid://117908944470249",
		ColorPickerVal = "rbxassetid://138329933807601",
		ColorPickerArrow = "rbxassetid://79353367608217",
		ColorPickerCrosshair = "rbxassetid://75007077378600",

		DropdownArrow = "rbxassetid://4918373417",
	},
}

return Assets
