local messages = {
	macroRequireError = "An error occured while requiring Macro '%s'",
	macroMethodError = "An error occured while running :%s for Macro '%s'",

	itemConstructorError = "An error occured while adding MacroItem '%s'",
	itemAlreadyRendered = "MacroItem '%s' has already been rendered.",

	invalidMacroType = "Expected Macro '%s' to return value of type table, got %s.",
	invalidItemContainer = "Invalid return value for MacroItem class '%s';\n%s",

	cannotFindClass = "Unable to find MacroItem class '%s'.",
}

return messages
