local Assets = {
	Images = {
		WidgetButtonDark = "rbxassetid://113567972662602",
		WidgetButtonLight = "rbxassetid://120966452330458",

		RefreshButtonDark = "rbxassetid://108378407847862",
		RefreshButtonLight = "rbxassetid://89128376547206",

		DefaultMacroIcon = "rbxassetid://95866080",
		MacroLoadingThrobber = "rbxassetid://2459243309",

		ColorPicker = {
			HueSat = "rbxassetid://117908944470249",
			Crosshair = "rbxassetid://75007077378600",
			Val = "rbxassetid://138329933807601",
			Arrow = "rbxassetid://79353367608217",
		},
		Dropdown = {
			Arrow = "rbxassetid://4918373417",
		},
		ScrollBar = {
			Top = "rbxassetid://6017290134",
			Middle = "rbxassetid://6017289904",
			Bottom = "rbxassetid://6017289712",
		},
	},
}

return Assets
