local Assets = {
	Images = {
		WidgetButton = "rbxassetid://95866080",
		RefreshButtonDark = "rbxassetid://17210895174",
		RefreshButtonLight = "rbxassetid://17210880996",

		DefaultMacroIcon = "rbxassetid://95866080",

		ColorPicker = {
			HueSat = "rbxassetid://117908944470249",
			Crosshair = "rbxassetid://75007077378600",
			Val = "rbxassetid://138329933807601",
			Arrow = "rbxassetid://79353367608217",
		},
		Dropdown = {
			Arrow = "rbxassetid://4918373417",
		},
	},
}

return Assets
